export const SAVE_REVIEW_REQUEST = "SAVE_REVIEW_REQUEST";
export const FETCH_REVIEW_REQUEST = "FETCH_REVIEW_REQUEST";
export const UPDATE_REVIEW_REQUEST = "UPDATE_REVIEW_REQUEST";
export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const REVIEW_SUCCESS = "REVIEW_SUCCESS";
export const REVIEW_FAILURE = "REVIEW_FAILURE";

