export const SAVE_JOB_REQUEST = "SAVE_JOB_REQUEST";
export const FETCH_JOB_REQUEST = "FETCH_JOB_REQUEST";
export const UPDATE_JOB_REQUEST = "UPDATE_JOB_REQUEST";
export const DELETE_JOB_REQUEST = "DELETE_JOB_REQUEST";
export const JOB_SUCCESS = "JOB_SUCCESS";
export const JOB_FAILURE = "JOB_FAILURE";

