export const SAVE_USER_REQUEST = "SAVE_USER_REQUEST";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";

