export const SAVE_REPORT_REQUEST = "SAVE_REPORT_REQUEST";
export const FETCH_REPORT_REQUEST = "FETCH_REPORT_REQUEST";
export const UPDATE_REPORT_REQUEST = "UPDATE_REPORT_REQUEST";
export const DELETE_REPORT_REQUEST = "DELETE_REPORT_REQUEST";
export const REPORT_SUCCESS = "REPORT_SUCCESS";
export const REPORT_FAILURE = "REPORT_FAILURE";

